In [2]:
import pandas as pd
import numpy as np

## Attributes

In [3]:
a1 = np.arange(3)
a2 = np.arange(6).reshape(2,3)
a3 = np.arange(18).reshape(2,3,3)

In [4]:
a1

array([0, 1, 2])

In [5]:
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [7]:
a1.shape , a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

In [8]:
a1.size , a2.size , a3.size

(3, 6, 18)

In [9]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [10]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

## Creating numpy arrays

In [12]:
ones = np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
random_array = np.random.randint(10 , size=(3,3))
random_array

array([[2, 4, 3],
       [8, 1, 6],
       [2, 3, 0]])

In [16]:
random_array_1 = np.random.rand(3,3)
random_array_1

array([[0.56053474, 0.67085639, 0.0213759 ],
       [0.57555561, 0.62277847, 0.21968787],
       [0.56470515, 0.64884858, 0.45527795]])

In [19]:
random_array_2 = np.random.random([3,3])
random_array_2

array([[0.80248945, 0.27002407, 0.25713291],
       [0.71243698, 0.21923906, 0.25685447],
       [0.63483923, 0.06342487, 0.94247318]])

In [20]:
# random seed

In [43]:
np.random.seed(2)
random_array_3 = np.random.randint(20 , size=(3,3))
random_array_3

array([[ 8, 15, 13],
       [ 8, 11, 18],
       [11,  8,  7]])

In [44]:
np.random.seed(2)
random_array_4 = np.random.randint(20 , size=(3,3))
random_array_4

array([[ 8, 15, 13],
       [ 8, 11, 18],
       [11,  8,  7]])

In [ ]:
# rsndom seed sets that when we run a  program with random seed set to some value it will replicate same random
# value each time